/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#7ad7c6",
        "surface-tint": "#4755b6",
        "on-primary-fixed": "#000d5f",
        "outline": "#767683",
        "on-error-container": "#93000a",
        "surface": "#f7f9fc",
        "primary": "#142588",
        "primary-fixed": "#dfe0ff",
        "tertiary-fixed-dim": "#ffb786",
        "surface-container": "#eceef1",
        "secondary": "#006b5e",
        "on-surface-variant": "#454652",
        "on-tertiary-container": "#ffa361",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7f9fc",
        "surface-container-high": "#e6e8eb",
        "on-secondary-container": "#006f62",
        "tertiary-fixed": "#ffdcc6",
        "on-primary-fixed-variant": "#2d3c9c",
        "on-primary": "#ffffff",
        "tertiary": "#542600",
        "background": "#f7f9fc",
        "on-tertiary-fixed-variant": "#723600",
        "surface-container-highest": "#e0e3e6",
        "on-primary-container": "#aab4ff",
        "inverse-on-surface": "#eff1f4",
        "tertiary-container": "#763800",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#bbc3ff",
        "primary-container": "#303f9f",
        "secondary-fixed": "#97f3e2",
        "surface-variant": "#e0e3e6",
        "error-container": "#ffdad6",
        "on-surface": "#191c1e",
        "on-background": "#191c1e",
        "inverse-primary": "#bbc3ff",
        "surface-container-low": "#f2f4f7",
        "on-secondary-fixed": "#00201b",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadd",
        "secondary-container": "#94f0df",
        "on-tertiary-fixed": "#311300",
        "outline-variant": "#c6c5d4",
        "on-secondary-fixed-variant": "#005047",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
